HomeWork4
TarasKostivi/homework pull request #4
Opened 2020-12-08 13:33 UTC by TarasKostivi

2020-12-08 13:43 UTC, ValentinTyhonov commented on src/homeWork4/Circle.java
> +        return diameter + diameter / 4 * 3.14;
площа = pi * diameter в квадраті / 4

2020-12-08 13:43 UTC, ValentinTyhonov commented on src/homeWork4/Circle.java
> +        return 3.14 * radius + radius;
тут так само, ти замість піднесення до квадрату використав додавання

2020-12-08 15:01 UTC, TarasKostivi commented on src/homeWork4/Circle.java
> +        return 3.14 * radius + radius;
ok

2020-12-10 00:12 UTC, ValentinTyhonov requested changes

2020-12-10 00:12 UTC, ValentinTyhonov commented on src/homeWork3/Main3.java
> +            for (int j = 1; j < i; i++){
цикл для заповнення масиву невірний. треба зовнішній (перший) цикл робити від 0 до array.length (тобто 5), а внутрішній (другий) - від 0 до array[i].length (тобто 7).

2020-12-11 19:59 UTC, merged